### PR TITLE
Easy way to decode json field to atom

### PR DESCRIPTION
**Pull request by yzprofile**
```erlang
-record(main, {
          test :: atom()
         }).

Record = #main{
            test = xxx
           },
Json = Record:to_json(),

Json = [{test,<<"xxx">>}].

{ok,{main,xxx}} = main:from_json(Json).
```

### CODE REVIEW

**Comment by lordnull** [comment]
Nice work on the pr, I like seeing tests updated with code. However, I don't think this is a feature I'll merge in. I never implemented this type of conversion because I have yet to see a valid use case for it.

If you have a trusted source that will never send random binaries to be converted to atoms, then you're better off listing off the atoms it uses anyway as a form of documentation.

If rec2json is used to transform untrusted data, it is a very bad idea to create atoms from that data since atoms are never garbage collected. A malicious source could fill up your atom table and crash the node.

The real fix here is likely to update the documentation to indicate all the above, rather than let a naive use of rec2json leave one open to a bad practice.

**Comment by yzprofile** [comment]
I know the issue of the GC.

In some situation, We have some rules' name is an atom() in our system, and we change it frequently.

We don't want to write `from_json` function for each record nor release system every time we change it.

You said it can be solved by defined another `atom_converter` type to work around this limit: https://github.com/lordnull/rec2json/issues/14

Why not make it easier to provide two choices.

Thanks.

**Comment by lordnull** [comment]
I hold the philosophy that a library should be 'safe by default'. Overriding those safeties needs to be a deliberate and conspicuous choice.

I discussed this is a peer to get another opinion. He felt that while the practice should be discouraged, it should also be possible. 

I think adding an exported type to rec2json may be an appropriate solution. It would use the existing user supplied types system, but be 'baked in' in a way.

Adding to r2j_types:

```erlang

-type unsafe_atom() :: atom().

-export_types([ unsafe_atom/0 ]).

-export([unsafe_atom/1]).

unsafe_atom(Binary) when is_binary(Binary) ->
    {ok, binary_to_atom(Binary, utf8)};

unsafe_atom(Atom) when is_atom(Atom) ->
    {ok, atom_to_binary(Atom, utf8)};

unsafe_atom(_) ->
    error.
````

And using it:
```erlang
-module(some_rec).

-record(some_rec, {
    atom_field = default_atom :: r2j_type:unsafe_atom(),
    another_field = 1 :: pos_integer()
}).
````

This should keep dialyzer happy, and allow you to do what you want (albiet not by using `atom()` but by using `r2j_types:unsafe_atom()`. It also has the added benefit of informing future developers/readers of your code that it was fully intentional to be converting atoms.

Would this be acceptable?

**Comment by yzprofile** [comment]
Thanks for your detailed explanation again.

Issue close.

**Comment by lordnull** [comment]
I've created a pr that may address this if you want to take a look: #18 .

**Comment by yzprofile** [comment]
That's a very clean way to do that,

Much better than mine.

Thanks for you awesome job and patience.

**Pull request closed without merging**
